homeassistant:
  name: Mark's House
  latitude: 42.4608
  longitude: -83.1407
  elevation: 197
  unit_system: metric
  time_zone: America/Detroit
  customize: !include customize.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
# enable frontent
frontend:
# enable configuration ui
config:
http:

# checks for updates
updater:
  include_used_components: true

system_health:


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
#map:

influxdb:
  host: localhost
  port: 8086
  database: home_assistant
  include:
    domains:
      - light
      - fan
      - sensor
      - binary_sensor
      - switch
      - yr
      - sun
      - group
      - device_tracker
      - input_select
      - input_text


#recorder:
#  #  purge_interval: 0
#  #purge_keep_days: 10
#  db_url: postgresql://@/hass


mqtt:
  broker: 127.0.0.1
  birth_message:
    topic: "tele/mark/hass/LWT"
    payload: "Online"
  will_message:
    topic: "tele/mark/hass/LWT"
    payload: "Offline"

apcupsd:
sun:
tts:
  - platform: google_translate
    service_name: google_say


shell_command:
  refresh_mqtt: '/home/hass/config/refresh_mtt.sh'

# included configs
group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml


#device_tracker:
#  - platform: unifi_direct
#    host: 192.168.1.3
#    verify_ssl: false
#    username: !secret unifi_user
#    password: !secret unifi_pass
#    new_device_defaults:
#      track_new_devices: False
#      hide_if_away: True

# include device configs
light: !include_dir_merge_list devices/light
sensor: !include_dir_merge_list devices/sensor
climate: !include_dir_merge_list devices/climate
