- platform: unifi_direct
  host: 192.168.1.3
  verify_ssl: false
  username: !secret unifi_user
  password: !secret unifi_pass
  new_device_defaults:
    track_new_devices: False
    hide_if_away: True
