- platform: template
  sensors:
    alisa_bedroom_light_time:
      friendly_name: 'alisa Bedroom Light Time'
      value_template: '{{ states.light.alisa_bedroom_light.attributes.Time }}'
    alisa_bedroom_light_uptime:
      friendly_name: 'alisa Bedroom Light Uptime'
      value_template: '{{ states.light.alisa_bedroom_light.attributes.Uptime }}'
    alisa_bedroom_light_vcc:
      friendly_name: 'alisa Bedroom Light Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.alisa_bedroom_light.attributes.Vcc }}'
    alisa_bedroom_light_heap:
      friendly_name: 'alisa Bedroom Light Heap'
      value_template: '{{ states.light.alisa_bedroom_light.attributes.Heap }}'
    alisa_bedroom_light_sleepmode:
      friendly_name: 'alisa Bedroom Light SleepMode'
      value_template: '{{ states.light.alisa_bedroom_light.attributes.SleepMode }}'
    alisa_bedroom_light_sleep:
      friendly_name: 'alisa Bedroom Light Sleep'
      value_template: '{{ states.light.alisa_bedroom_light.attributes.Sleep }}'
    alisa_bedroom_light_loadavg:
      friendly_name: 'alisa Bedroom Light LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.alisa_bedroom_light.attributes.LoadAvg }}'
    alisa_bedroom_light_wifi_ssid:
      friendly_name: 'alisa Bedroom Light Wifi SSId'
      value_template: "{{ state_attr('light.alisa_bedroom_light', 'Wifi')['SSId'] }}"
    alisa_bedroom_light_wifi_bssid:
      friendly_name: 'alisa Bedroom Light Wifi BSSId'
      value_template: "{{ state_attr('light.alisa_bedroom_light', 'Wifi')['BSSId'] }}"
    alisa_bedroom_light_wifi_channel:
      friendly_name: 'alisa Bedroom Light Wifi Channel'
      value_template: "{{ state_attr('light.alisa_bedroom_light', 'Wifi')['Channel'] }}"
    alisa_bedroom_light_wifi_rssi:
      friendly_name: 'alisa Bedroom Light Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.alisa_bedroom_light', 'Wifi')['RSSI'] }}"
    alisa_bedroom_light_wifi_linkcount:
      friendly_name: 'alisa Bedroom Light Wifi Link Count'
      value_template: "{{ state_attr('light.alisa_bedroom_light', 'Wifi')['LinkCount'] }}"
    alisa_bedroom_light_wifi_downtime:
      friendly_name: 'alisa Bedroom Light Wifi Downtime'
      value_template: "{{ state_attr('light.alisa_bedroom_light', 'Wifi')['Downtime'] }}"

    alisa_bedroom_light_power:
      friendly_name: 'alisa Bedroom Light Power'
      value_template: '{{ states.light.alisa_bedroom_light.attributes.POWER }}'
