- platform: template
  sensors:
    basement_light_004_time:
      friendly_name: 'Basement Light 004 Time'
      value_template: '{{ states.light.basement_light_004.attributes.Time }}'
    basement_light_004_uptime:
      friendly_name: 'Basement Light 004 Uptime'
      value_template: '{{ states.light.basement_light_004.attributes.Uptime }}'
    basement_light_004_vcc:
      friendly_name: 'Basement Light 004 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.basement_light_004.attributes.Vcc }}'
    basement_light_004_heap:
      friendly_name: 'Basement Light 004 Heap'
      value_template: '{{ states.light.basement_light_004.attributes.Heap }}'
    basement_light_004_sleepmode:
      friendly_name: 'Basement Light 004 SleepMode'
      value_template: '{{ states.light.basement_light_004.attributes.SleepMode }}'
    basement_light_004_sleep:
      friendly_name: 'Basement Light 004 Sleep'
      value_template: '{{ states.light.basement_light_004.attributes.Sleep }}'
    basement_light_004_loadavg:
      friendly_name: 'Basement Light 004 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.basement_light_004.attributes.LoadAvg }}'
    basement_light_004_wifi_ssid:
      friendly_name: 'Basement Light 004 Wifi SSId'
      value_template: "{{ state_attr('light.basement_light_004', 'Wifi')['SSId'] }}"
    basement_light_004_wifi_bssid:
      friendly_name: 'Basement Light 004 Wifi BSSId'
      value_template: "{{ state_attr('light.basement_light_004', 'Wifi')['BSSId'] }}"
    basement_light_004_wifi_channel:
      friendly_name: 'Basement Light 004 Wifi Channel'
      value_template: "{{ state_attr('light.basement_light_004', 'Wifi')['Channel'] }}"
    basement_light_004_wifi_rssi:
      friendly_name: 'Basement Light 004 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.basement_light_004', 'Wifi')['RSSI'] }}"
    basement_light_004_wifi_linkcount:
      friendly_name: 'Basement Light 004 Wifi Link Count'
      value_template: "{{ state_attr('light.basement_light_004', 'Wifi')['LinkCount'] }}"
    basement_light_004_wifi_downtime:
      friendly_name: 'Basement Light 004 Wifi Downtime'
      value_template: "{{ state_attr('light.basement_light_004', 'Wifi')['Downtime'] }}"

    basement_light_004_power:
      friendly_name: 'Basement Light 004 Power'
      value_template: '{{ states.light.basement_light_004.attributes.POWER }}'
