- platform: template
  sensors:
    basement_light_008_time:
      friendly_name: 'Basement Light 008 Time'
      value_template: '{{ states.light.basement_light_008.attributes.Time }}'
    basement_light_008_uptime:
      friendly_name: 'Basement Light 008 Uptime'
      value_template: '{{ states.light.basement_light_008.attributes.Uptime }}'
    basement_light_008_vcc:
      friendly_name: 'Basement Light 008 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.basement_light_008.attributes.Vcc }}'
    basement_light_008_heap:
      friendly_name: 'Basement Light 008 Heap'
      value_template: '{{ states.light.basement_light_008.attributes.Heap }}'
    basement_light_008_sleepmode:
      friendly_name: 'Basement Light 008 SleepMode'
      value_template: '{{ states.light.basement_light_008.attributes.SleepMode }}'
    basement_light_008_sleep:
      friendly_name: 'Basement Light 008 Sleep'
      value_template: '{{ states.light.basement_light_008.attributes.Sleep }}'
    basement_light_008_loadavg:
      friendly_name: 'Basement Light 008 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.basement_light_008.attributes.LoadAvg }}'
    basement_light_008_wifi_ssid:
      friendly_name: 'Basement Light 008 Wifi SSId'
      value_template: "{{ state_attr('light.basement_light_008', 'Wifi')['SSId'] }}"
    basement_light_008_wifi_bssid:
      friendly_name: 'Basement Light 008 Wifi BSSId'
      value_template: "{{ state_attr('light.basement_light_008', 'Wifi')['BSSId'] }}"
    basement_light_008_wifi_channel:
      friendly_name: 'Basement Light 008 Wifi Channel'
      value_template: "{{ state_attr('light.basement_light_008', 'Wifi')['Channel'] }}"
    basement_light_008_wifi_rssi:
      friendly_name: 'Basement Light 008 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.basement_light_008', 'Wifi')['RSSI'] }}"
    basement_light_008_wifi_linkcount:
      friendly_name: 'Basement Light 008 Wifi Link Count'
      value_template: "{{ state_attr('light.basement_light_008', 'Wifi')['LinkCount'] }}"
    basement_light_008_wifi_downtime:
      friendly_name: 'Basement Light 008 Wifi Downtime'
      value_template: "{{ state_attr('light.basement_light_008', 'Wifi')['Downtime'] }}"

    basement_light_008_power:
      friendly_name: 'Basement Light 008 Power'
      value_template: '{{ states.light.basement_light_008.attributes.POWER }}'
