- platform: template
  sensors:
    basement_light_005_time:
      friendly_name: 'Basement Light 005 Time'
      value_template: '{{ states.light.basement_light_005.attributes.Time }}'
    basement_light_005_uptime:
      friendly_name: 'Basement Light 005 Uptime'
      value_template: '{{ states.light.basement_light_005.attributes.Uptime }}'
    basement_light_005_vcc:
      friendly_name: 'Basement Light 005 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.basement_light_005.attributes.Vcc }}'
    basement_light_005_heap:
      friendly_name: 'Basement Light 005 Heap'
      value_template: '{{ states.light.basement_light_005.attributes.Heap }}'
    basement_light_005_sleepmode:
      friendly_name: 'Basement Light 005 SleepMode'
      value_template: '{{ states.light.basement_light_005.attributes.SleepMode }}'
    basement_light_005_sleep:
      friendly_name: 'Basement Light 005 Sleep'
      value_template: '{{ states.light.basement_light_005.attributes.Sleep }}'
    basement_light_005_loadavg:
      friendly_name: 'Basement Light 005 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.basement_light_005.attributes.LoadAvg }}'
    basement_light_005_wifi_ssid:
      friendly_name: 'Basement Light 005 Wifi SSId'
      value_template: "{{ state_attr('light.basement_light_005', 'Wifi')['SSId'] }}"
    basement_light_005_wifi_bssid:
      friendly_name: 'Basement Light 005 Wifi BSSId'
      value_template: "{{ state_attr('light.basement_light_005', 'Wifi')['BSSId'] }}"
    basement_light_005_wifi_channel:
      friendly_name: 'Basement Light 005 Wifi Channel'
      value_template: "{{ state_attr('light.basement_light_005', 'Wifi')['Channel'] }}"
    basement_light_005_wifi_rssi:
      friendly_name: 'Basement Light 005 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.basement_light_005', 'Wifi')['RSSI'] }}"
    basement_light_005_wifi_linkcount:
      friendly_name: 'Basement Light 005 Wifi Link Count'
      value_template: "{{ state_attr('light.basement_light_005', 'Wifi')['LinkCount'] }}"
    basement_light_005_wifi_downtime:
      friendly_name: 'Basement Light 005 Wifi Downtime'
      value_template: "{{ state_attr('light.basement_light_005', 'Wifi')['Downtime'] }}"

    basement_light_005_power:
      friendly_name: 'Basement Light 005 Power'
      value_template: '{{ states.light.basement_light_005.attributes.POWER }}'
