- platform: template
  sensors:
    bedroom_light_time:
      friendly_name: 'Bedroom Light Time'
      value_template: '{{ states.light.bedroom_light.attributes.Time }}'
    bedroom_light_uptime:
      friendly_name: 'Bedroom Light Uptime'
      value_template: '{{ states.light.bedroom_light.attributes.Uptime }}'
    bedroom_light_vcc:
      friendly_name: 'Bedroom Light Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.bedroom_light.attributes.Vcc }}'
    bedroom_light_heap:
      friendly_name: 'Bedroom Light Heap'
      value_template: '{{ states.light.bedroom_light.attributes.Heap }}'
    bedroom_light_sleepmode:
      friendly_name: 'Bedroom Light SleepMode'
      value_template: '{{ states.light.bedroom_light.attributes.SleepMode }}'
    bedroom_light_sleep:
      friendly_name: 'Bedroom Light Sleep'
      value_template: '{{ states.light.bedroom_light.attributes.Sleep }}'
    bedroom_light_loadavg:
      friendly_name: 'Bedroom Light LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.bedroom_light.attributes.LoadAvg }}'
    bedroom_light_wifi_ssid:
      friendly_name: 'Bedroom Light Wifi SSId'
      value_template: "{{ state_attr('light.bedroom_light', 'Wifi')['SSId'] }}"
    bedroom_light_wifi_bssid:
      friendly_name: 'Bedroom Light Wifi BSSId'
      value_template: "{{ state_attr('light.bedroom_light', 'Wifi')['BSSId'] }}"
    bedroom_light_wifi_channel:
      friendly_name: 'Bedroom Light Wifi Channel'
      value_template: "{{ state_attr('light.bedroom_light', 'Wifi')['Channel'] }}"
    bedroom_light_wifi_rssi:
      friendly_name: 'Bedroom Light Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.bedroom_light', 'Wifi')['RSSI'] }}"
    bedroom_light_wifi_linkcount:
      friendly_name: 'Bedroom Light Wifi Link Count'
      value_template: "{{ state_attr('light.bedroom_light', 'Wifi')['LinkCount'] }}"
    bedroom_light_wifi_downtime:
      friendly_name: 'Bedroom Light Wifi Downtime'
      value_template: "{{ state_attr('light.bedroom_light', 'Wifi')['Downtime'] }}"

    bedroom_light_power:
      friendly_name: 'Bedroom Light Power'
      value_template: '{{ states.light.bedroom_light.attributes.POWER }}'
