- platform: mqtt
  name: 'Basement Light 001'
  state_topic: 'stat/mark/basement/lights/001/POWER'
  command_topic: 'cmnd/mark/basement/lights/001/POWER'
  json_attributes_topic: 'tele/mark/basement/lights/001/STATE'
  availability_topic: 'tele/mark/basement/lights/001/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
  payload_on: 'ON'
  payload_off: 'OFF'
