- platform: mqtt
  name: 'Bedroom Light'
  state_topic: 'stat/mark/bedroom/lights/POWER'
  command_topic: 'cmnd/mark/bedroom/lights/POWER'
  json_attributes_topic: 'tele/mark/bedroom/lights/STATE'
  availability_topic: 'tele/mark/bedroom/lights/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
  payload_on: 'ON'
  payload_off: 'OFF'
