- platform: mqtt
  name: "Thermostat Ambient Temperature"
  state_topic: "tele/mark/thermostat/sensors"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temperature }}'
  force_update: True

- platform: mqtt
  name: "Thermostat Ambient Pressure"
  state_topic: "tele/mark/thermostat/sensors"
  unit_of_measurement: "Pa"
  value_template: '{{ value_json.pressure }}'
  force_update: True

- platform: template
  sensors:
    thermostat_pressure_kpa:
      friendly_name: "Ambient Pressure"
      unit_of_measurement: 'kPa'
      value_template: "{{ ((states('sensor.thermostat_ambient_pressure') | multiply(1/1000)) | float) | round(1) }}"

- platform: mqtt
  name: "Thermostat Ambient Humidity"
  state_topic: "tele/mark/thermostat/sensors"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity }}'
  force_update: True

- platform: mqtt
  name: "Thermostat Target Temperature"
  state_topic: "tele/mark/thermostat/input"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.target }}'
  force_update: True

- platform: mqtt
  name: "Thermostat Requested State"
  state_topic: "tele/mark/thermostat/input"
  value_template: '{{ value_json.mode }}'
  force_update: True

- platform: mqtt
  name: "Thermostat Requested Fan State"
  state_topic: "tele/mark/thermostat/input"
  value_template: '{{ value_json.fan }}'
  force_update: True

- platform: mqtt
  name: "Thermostat Swing"
  state_topic: "tele/mark/thermostat/input"
  value_template: '{{ value_json.swing }}'
  force_update: True

- platform: mqtt
  name: "Thermostat Timeout"
  state_topic: "tele/mark/thermostat/input"
  value_template: '{{ value_json.timeout }}'
  unit_of_measurement: "ms"
  force_update: True

- platform: template
  sensors:
    thermostat_timeout_human_readable:
      friendly_name: "Thermostat Reset Timeout"
      unit_of_measurement: "hours"
      value_template: "{{ states('sensor.Office_Thermostat_Timeout') | float / 3600000 | round(1) }}"

- platform: mqtt
  name: "Thermostat Active State"
  state_topic: "tele/mark/thermostat/output"
  value_template: '{{ value_json.state }}'
  force_update: True

- platform: mqtt
  name: "Thermostat Active Fan State"
  state_topic: "tele/mark/thermostat/output"
  value_template: '{{ value_json.fan }}'
  force_update: True

- platform: mqtt
  name: "Thermostat Power Source"
  state_topic: "tele/mark/thermostat/sensors"
  value_template: '{{ value_json.powerSource }}'
  force_update: True

- platform: template
  sensors:
    thermostat_temp_on:
      friendly_name: "Thermostat Temp On"
      unit_of_measurement: "°C"
      value_template: >-
        {% if states.sensor.thermostat_active_state.state | string == "cool" or states.sensor.thermostat_active_state.state | string == "heat" %}
        {{states.sensor.thermostat_ambient_temperature.state | float }}
        {% endif %}
